// <auto-generated />
namespace MvcApplication2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class hjyffd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hjyffd));
        
        string IMigrationMetadata.Id
        {
            get { return "201508280114312_hjyffd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
