//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int estudianteId { get; set; }
        public string tipo_documento { get; set; }
        public string num_documento { get; set; }
        public int codigo { get; set; }
        public string clave { get; set; }
        public int programaId { get; set; }
        public int hojaVidaId { get; set; }
        public int rotacionId { get; set; }
        public string direccion_procedencia { get; set; }
        public string barrio_procedencia { get; set; }
        public string telefono_procedencia { get; set; }
        public string modalidad { get; set; }
        public short semestre { get; set; }
        public string estado_academico { get; set; }
    
        public virtual HojaVidas HojaVidas { get; set; }
        public virtual Rotacions Rotacions { get; set; }
    }
}
