//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HojaVidas
    {
        public HojaVidas()
        {
            this.Estudiantes = new HashSet<Estudiantes>();
        }
    
        public int hojaVidaId { get; set; }
        public string primer_nombre { get; set; }
        public string segundo_nombre { get; set; }
        public string primer_apellido { get; set; }
        public string segundo_apellido { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string hemoclasificacion { get; set; }
        public string genero { get; set; }
        public string estado_civil { get; set; }
        public short hijos { get; set; }
        public string imagen_DI { get; set; }
        public long num_telefono { get; set; }
        public long num_celular { get; set; }
        public string correo { get; set; }
        public string entidad_salud { get; set; }
        public string estado_afiliacion { get; set; }
        public string regimen { get; set; }
        public string tipo_afiliacion { get; set; }
        public bool estado_HV { get; set; }
        public string ARL { get; set; }
        public string certificado_ARL { get; set; }
        public Nullable<int> familiaId { get; set; }
        public string facultad { get; set; }
        public string departamento_procedencia { get; set; }
        public string municipio_procedencia { get; set; }
        public string direccion_manizales { get; set; }
    
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
    }
}
