//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rotacions
    {
        public Rotacions()
        {
            this.Estudiantes = new HashSet<Estudiantes>();
        }
    
        public int rotacionId { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_terminacion { get; set; }
        public string horario { get; set; }
        public short periodo_academico { get; set; }
        public int IPS_ESEId { get; set; }
        public string grupo { get; set; }
        public int year_academico { get; set; }
        public int numero_estudiantes { get; set; }
        public int actividadacademicaId { get; set; }
    
        public virtual ICollection<Estudiantes> Estudiantes { get; set; }
    }
}
