//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActividadAcademica
    {

        public int actividadacademicaId { get; set; } 
        public string tipo { get; set; }
        public string asignatura { get; set; }
        public string codigo_AA { get; set; }        
        public string nombre { get; set; }
        public string modalidad_practica { get; set; }
       public int grupo_maximo { get; set; }
       public int max_estudiantes_rotacion { get; set; }
       
        public int DepartamentoSaludId { get; set; }//sale? 
        public int servicioId { get; set; }

        public virtual IPS_ESE IPS_ESE { get; set; }
 
        public virtual DepartamentoSalud DepartamentoSalud { get; set; }
        public virtual ICollection<Rotacion> Rotacion { get; set; }
      
    
       
        
    }
}
