//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartamentoSalud
    {
        public DepartamentoSalud()
        {
            this.Docente = new HashSet<Docente>();
            this.Postgrado = new HashSet<Postgrado>();
        }

        public int DepartamentoSaludId { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string director_departamento { get; set; }

        public string codigo { get; set; }
        public string user { get; set; }
        public virtual ICollection<ActividadAcademica> ActividadAcademica { get; set; }
        
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<Postgrado> Postgrado { get; set; }
    }
}
