//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Docente
    {
        public int docenteId { get; set; }
        public string tipo_documento { get; set; }
        public string num_documento { get; set; }
        public string num_libreta_militar { get; set; }
        public string clave { get; set; }
        public string titulo_pregrado { get; set; }
        public string maximo_nivel_formacion { get; set; }
        public string dedicacion { get; set; }
        public string tipo_vinculacion { get; set; }
        public string categoria_escalafon_docente { get; set; }
        public string imagen_acta_grado { get; set; }
        public string diploma_profesional { get; set; }
        public string certificado_DPE { get; set; }
       
        public string certificado_TPDTS { get; set; }
        public string certificado_TPN { get; set; }
        public string otro_titulo { get; set; }
      
        public int hojaVidaId { get; set; }
        public int DepartamentoSaludId { get; set; } 
        public int rotacionId { get; set; } 
    
        public virtual DepartamentoSalud DepartamentoSalud { get; set; }
    
        public virtual HojaVida HojaVida { get; set; }
        public virtual Rotacion Rotacion { get; set; }
    }

    public class DocenteWS
    {



        public string CEDULA { get; set; }

        public string NOMBRE { get; set; }

        public string P_APELLIDO { get; set; }

        public string S_APELLIDO { get; set; }

        public string LIBREMIL { get; set; }
        public string FECHANAC { get; set; }

        public string DIRECCION { get; set; }

        public string TELEFONO { get; set; }

        public string EMAIL { get; set; }
        public string NOM_FACULTAD { get; set; }
        public string NOM_DEPTO { get; set; }

        public string CHIN_TITULO { get; set; }
        public string CNIA_DESCRIPCION { get; set; }


        public string CTUR_DESCRIPCION { get; set; }

        public string CHOV_LUGARNACE { get; set; }

        public string CHOV_SEXO { get; set; }

        


        public class ESObject0
        {
            public List<DocenteWS> datosProfesor { get; set; }
        }
    }
       

}
