//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int estudianteId { get; set; }
        public string tipo_documento { get; set; }
        public string num_documento { get; set; }
        public long codigo { get; set; }
        public string direccion_procedencia { get; set; }
        public string barrio_procedencia { get; set; }
        public string telefono_procedencia { get; set; }
        public string clave { get; set; }
        public string modalidad { get; set; }
        public int programaId { get; set; }
        public short semestre { get; set; }     
        public String estado_academico { get; set; }
        public int hojaVidaId { get; set; }
        public int rotacionId { get; set; }
        
    
        public virtual HojaVida HojaVida{ get; set; }
        public virtual Programa Programa { get; set; }
        public virtual Rotacion Rotacion { get; set; }
    }

    public class EstudianteWS
    {



        public string NUM_DOC { get; set; }

        public string CODIGO { get; set; }

        public string NOMBRE { get; set; }

        public string P_APELLIDO { get; set; }

        public string S_APELLIDO { get; set; }
        public string FECHA_NACIMIENTO { get; set; }

        public string EMAIL { get; set; }
        public string MUN_PROC { get; set; }
        
        public string DIR_CORREO { get; set; }

        public string TEL_CORREO { get; set; }
        public string NOM_FACULTAD { get; set; }
        public string NOM_CARRERA { get; set; }

        public string NOM_ESTADO { get; set; }
         public string SEXO { get; set; }
         public string NOM_DOC { get; set; }
         public string MODALIDAD { get; set; }

         public string SEMESTRE { get; set; }
            
            
            
       


        public class ESObject0
        {
            public List<EstudianteWS> datosEstudiante { get; set; }
        }
    }
}
