//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPS_ESE
    {
        public IPS_ESE()
        {
           
           
        }

        public int IPS_ESEId { get; set; }
        public string origen { get; set; }
        public string nombre { get; set; }
        public string representante_legal { get; set; }
        public string cargo { get; set; }
        public string correo { get; set; }
        public string naturaleza_juridica { get; set; }
        public short nivel_complejidad { get; set; }
        public string representanteDS { get; set; }
        public string cargo_representanteDS { get; set; }
        public string corregimiento_o_vereda { get; set; }
        public string objeto_convenio { get; set; }
        public int municipioId { get; set; }
    
        public virtual ICollection<IPS_ESE_Servicio> IPS_ESE_Servicio { get; set; }
        public virtual ICollection<Rotacion> Rotaciones { get; set; }
        public virtual Municipio Municipio { get; set; }
    }
}
