//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class IPS_ESE
    {
        public IPS_ESE()
        {
           
           
        }

        public int IPS_ESEId { get; set; }
        [Required]
        public string direccion { get; set; }
        [Required]
        public string nombre { get; set; }
        [Required]
        [RegularExpression("([1-9][0-9]*)", ErrorMessage = "Campo númerico")]            
        public string telefono { get; set; }
        public string fax { get; set; }
        [Required]
        public string correo { get; set; }
        public string naturaleza_juridica { get; set; }
        public short nivel_complejidad { get; set; }
        [Required]
        public string representante { get; set; }
        
       
        [Required]
        public string representanteDS { get; set; }
        public string cargo_representanteDS { get; set; }
       
        [Required]
        public string representante_legal { get; set; }//Para carta de presentacion
        [Required]
        public string cargo { get; set; }//cargo para carta de presentacion

        [Required]
        public string user { get; set; }

        [Required]
        public string pass { get; set; }

        [Required]
        public string passC { get; set; }
        
       
        
        [Range(3000000000, 3999999999)]
        public long num_celular { get; set; }
        public string objeto_convenio { get; set; }
        public int municipioId { get; set; }
    
        public virtual ICollection<IPS_ESE_Servicio> IPS_ESE_Servicio { get; set; }
        public virtual ICollection<Rotacion> Rotaciones { get; set; }
        public virtual Municipio Municipio { get; set; }
    }
}
