//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPS_ESE_Servicio
    {
        public int IPS_ESE_ServicioId { get; set; }
        public int IPS_ESEId { get; set; }
        public int servicioId { get; set; }
    
        public virtual IPS_ESE IPS_ESE { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
