//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using MvcApplication2.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebaEntities : DbContext
    {
        public pruebaEntities()
            : base("name=pruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public Db <ActividadAcademica > ActividadAcademica  { get;  ; }
        public Db <Adulto > Adulto  { get;  ; }
        public Db <Carne > Carne  { get;  ; }
        public Db <Convenio_IES > Convenio_IES  { get;  ; }
        public Db <DepartamentoSalud > DepartamentoSalud  { get;  ; }
        public Db <Departamento > Departamento  { get;  ; }
        public Db <Docente > Docente  { get;  ; }
        public Db <Estudiante > Estudiante  { get;  ; }
        public Db <Fabricante > Fabricante  { get;  ; }
        public Db <Facultad > Facultad  { get;  ; }
        public Db <Familia > Familia  { get;  ; }
        public Db <Funcionario > Funcionario  { get;  ; }
        public Db <HojaVida > HojaVida  { get;  ; }
        public Db <IES > IES  { get;  ; }
        public Db <InfanciaMenor 1> InfanciaMenor 1 { get;  ; }
        public Db <IPS_ESE_Rotacion > IPS_ESE_Rotacion  { get;  ; }
        public Db <IPS_ESE_Servicio > IPS_ESE_Servicio  { get;  ; }
        public Db <IPS_ESE > IPS_ESE  { get;  ; }
        public Db <IPS_vacunadora > IPS_vacunadora  { get;  ; }
        public Db <Laboratorio 1> Laboratorio 1 { get;  ; }
        public Db <Municipio > Municipio  { get;  ; }
        public Db <Postgrado > Postgrado  { get;  ; }
        public Db <Programa > Programa  { get;  ; }
        public Db <ReaccionesAdversas > ReaccionesAdversas  { get;  ; }
        public Db <Reaccion > Reaccion  { get;  ; }
        public Db <Rotacion > Rotacion  { get;  ; }
        public Db <Servicio > Servicio  { get;  ; }
        public Db <TipoVacuna > TipoVacuna  { get;  ; }
        public Db <Usuario > Usuario  { get;  ; }
        public Db <Vacuna > Vacuna  { get;  ; }
    }
}
