//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public Municipio()
        {
 
        }
    
        public int municipioId { get; set; }
        public string nombre { get; set; }
        public int departamentoId { get; set; }
    
        public virtual Departamento Departamento { get; set; }
     
        public virtual ICollection<IPS_ESE> IPS_ESE { get; set; }
    }
}
