//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postgrado
    {
        public int postgradoId { get; set; }
        public short tipo_postgrado { get; set; }
        public string nombre { get; set; }
        public int departamento_saludId { get; set; }
    
        public virtual DepartamentoSalud DepartamentoSalud { get; set; }
    }
}
