//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programa
    {
        public Programa()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int programaId { get; set; }
        public string  nombre { get; set; }
        public string nivel_formacion { get; set; }
        public string director_programa { get; set; }
        public string tipo { get; set; }
        public string modalidad { get; set; }
        public string codigo { get; set; }
    
        public virtual ICollection<Estudiante> Estudiante { get; set; }
    }
}
