//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web;
    
    public partial class Rotacion
    {
        public Rotacion()
        {
            this.Docente = new HashSet<Docente>();
            this.Estudiante = new HashSet<Estudiante>();
          
         }
     
        public int rotacionId { get; set; }
        public string grupo { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime fecha_inicio { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime fecha_terminacion { get; set; }
        public string horario { get; set; }  
        public int year_academico { get; set; } 
        public short periodo_academico { get; set; }

        [Required]
        public int numero_estudiantes { get; set; }//dice cuantos estudiantes estan inscritos en la rotacion
       
       
        
        public int IPS_ESEId { get; set; }

        public int actividadacademicaId { get; set; } 
       
        public virtual ActividadAcademica ActividadAcademica { get; set; }
        
        public virtual IPS_ESE IPS_ESE { get; set; }

                
        public virtual ICollection<Docente> Docente { get; set; }
        public virtual ICollection<Estudiante> Estudiante { get; set; }
      
    }
    public class Grupos
    {



        public string COD_MATERIA { get; set; }

        public string NOM_MATERIA { get; set; }

        public string GRUPO { get; set; }

        public string FECHA_INICIO { get; set; }

        public string FECHA_FINAL { get; set; }
        public int ANO { get; set; }
        public short PERIODO { get; set; }
        public int INSCRITOS { get; set; }
        public string PROGRAMA { get; set; }
        public class ESObject0
        {
            public List<Grupos> gruposMaterias { get; set; }
        }

    }
    public class GruposInscritos
    {



        public string CODIGO { get; set; }

        public string CEDULA_PROFESOR { get; set; }


        public class ESObject0
        {
            public List<GruposInscritos> inscritosGrupo { get; set; }
        }

    }
}
