//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RotacionEstudiante
    {
        public RotacionEstudiante()
        {
           
          
         }

        public int rotacionEstudianteId { get; set; }
        public int rotacionId { get; set; }    
        
        public int IPS_ESEId { get; set; }
        public int docenteId { get; set; }
        public int estudianteId { get; set; }


      
        public string horario { get; set; }
       
        public virtual IPS_ESE IPS_ESE { get; set; }
        public virtual Rotacion Rotacion { get; set; }

        public virtual Docente Docente { get; set; }
        public virtual Estudiante Estudiante { get; set; }
      
    }
}
