//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public Servicio()
        {
            this.ActividadAcademica = new HashSet<ActividadAcademica>();
            this.IPS_ESE_Servicio = new HashSet<IPS_ESE_Servicio>();
        }
    
        public int servicioId { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ActividadAcademica> ActividadAcademica { get; set; }
        public virtual ICollection<IPS_ESE_Servicio> IPS_ESE_Servicio { get; set; }
    }
}
