//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Vacuna
    {
   
        public int vacunaId { get; set; }
        public string nombre_generico { get; set; }
        public string laboratorioOtro { get; set; }//antes:antigenos_contenidos
        [Required]
        public string lote { get; set; }
        public string lugar_anatomico { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_vacunacion { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_prox_vacunacion { get; set; }

        public string laboratorio_vacunacion { get; set; }
        public string observaciones { get; set; }
 
        public int hojaVidaId { get; set; }

        

        public virtual HojaVida HojaVida { get; set; }
 
    }
}
