//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSFacultadSaludSoap")]
    public interface WSFacultadSaludSoap {
        
        // CODEGEN: Generating message contract since element name cod_carrera from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEstudiantesMatriculados", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponse getEstudiantesMatriculados(MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEstudiantesMatriculados", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponse> getEstudiantesMatriculadosAsync(MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest request);
        
        // CODEGEN: Generating message contract since element name cod_depto from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProfesoresActivos", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getProfesoresActivosResponse getProfesoresActivos(MvcApplication2.ServiceReference1.getProfesoresActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProfesoresActivos", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getProfesoresActivosResponse> getProfesoresActivosAsync(MvcApplication2.ServiceReference1.getProfesoresActivosRequest request);
        
        // CODEGEN: Generating message contract since element name num_doc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDatosEstudiante", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getDatosEstudianteResponse getDatosEstudiante(MvcApplication2.ServiceReference1.getDatosEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDatosEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getDatosEstudianteResponse> getDatosEstudianteAsync(MvcApplication2.ServiceReference1.getDatosEstudianteRequest request);
        
        // CODEGEN: Generating message contract since element name num_doc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDatosProfesor", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getDatosProfesorResponse getDatosProfesor(MvcApplication2.ServiceReference1.getDatosProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDatosProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getDatosProfesorResponse> getDatosProfesorAsync(MvcApplication2.ServiceReference1.getDatosProfesorRequest request);
        
        // CODEGEN: Generating message contract since element name getMateriasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterias", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getMateriasResponse getMaterias(MvcApplication2.ServiceReference1.getMateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterias", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getMateriasResponse> getMateriasAsync(MvcApplication2.ServiceReference1.getMateriasRequest request);
        
        // CODEGEN: Generating message contract since element name cod_materia from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGruposMateria", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getGruposMateriaResponse getGruposMateria(MvcApplication2.ServiceReference1.getGruposMateriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGruposMateria", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getGruposMateriaResponse> getGruposMateriaAsync(MvcApplication2.ServiceReference1.getGruposMateriaRequest request);
        
        // CODEGEN: Generating message contract since element name cod_materia from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInscritosGrupo", ReplyAction="*")]
        MvcApplication2.ServiceReference1.getInscritosGrupoResponse getInscritosGrupo(MvcApplication2.ServiceReference1.getInscritosGrupoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInscritosGrupo", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getInscritosGrupoResponse> getInscritosGrupoAsync(MvcApplication2.ServiceReference1.getInscritosGrupoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEstudiantesMatriculadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEstudiantesMatriculados", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequestBody Body;
        
        public getEstudiantesMatriculadosRequest() {
        }
        
        public getEstudiantesMatriculadosRequest(MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEstudiantesMatriculadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_carrera;
        
        public getEstudiantesMatriculadosRequestBody() {
        }
        
        public getEstudiantesMatriculadosRequestBody(string cod_carrera) {
            this.cod_carrera = cod_carrera;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEstudiantesMatriculadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEstudiantesMatriculadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponseBody Body;
        
        public getEstudiantesMatriculadosResponse() {
        }
        
        public getEstudiantesMatriculadosResponse(MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getEstudiantesMatriculadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getEstudiantesMatriculadosResult;
        
        public getEstudiantesMatriculadosResponseBody() {
        }
        
        public getEstudiantesMatriculadosResponseBody(string getEstudiantesMatriculadosResult) {
            this.getEstudiantesMatriculadosResult = getEstudiantesMatriculadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProfesoresActivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProfesoresActivos", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getProfesoresActivosRequestBody Body;
        
        public getProfesoresActivosRequest() {
        }
        
        public getProfesoresActivosRequest(MvcApplication2.ServiceReference1.getProfesoresActivosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProfesoresActivosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_depto;
        
        public getProfesoresActivosRequestBody() {
        }
        
        public getProfesoresActivosRequestBody(string cod_depto) {
            this.cod_depto = cod_depto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProfesoresActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProfesoresActivosResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getProfesoresActivosResponseBody Body;
        
        public getProfesoresActivosResponse() {
        }
        
        public getProfesoresActivosResponse(MvcApplication2.ServiceReference1.getProfesoresActivosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProfesoresActivosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProfesoresActivosResult;
        
        public getProfesoresActivosResponseBody() {
        }
        
        public getProfesoresActivosResponseBody(string getProfesoresActivosResult) {
            this.getProfesoresActivosResult = getProfesoresActivosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatosEstudianteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatosEstudiante", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getDatosEstudianteRequestBody Body;
        
        public getDatosEstudianteRequest() {
        }
        
        public getDatosEstudianteRequest(MvcApplication2.ServiceReference1.getDatosEstudianteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDatosEstudianteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string num_doc;
        
        public getDatosEstudianteRequestBody() {
        }
        
        public getDatosEstudianteRequestBody(string num_doc) {
            this.num_doc = num_doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatosEstudianteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatosEstudianteResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getDatosEstudianteResponseBody Body;
        
        public getDatosEstudianteResponse() {
        }
        
        public getDatosEstudianteResponse(MvcApplication2.ServiceReference1.getDatosEstudianteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDatosEstudianteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDatosEstudianteResult;
        
        public getDatosEstudianteResponseBody() {
        }
        
        public getDatosEstudianteResponseBody(string getDatosEstudianteResult) {
            this.getDatosEstudianteResult = getDatosEstudianteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatosProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatosProfesor", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getDatosProfesorRequestBody Body;
        
        public getDatosProfesorRequest() {
        }
        
        public getDatosProfesorRequest(MvcApplication2.ServiceReference1.getDatosProfesorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDatosProfesorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string num_doc;
        
        public getDatosProfesorRequestBody() {
        }
        
        public getDatosProfesorRequestBody(string num_doc) {
            this.num_doc = num_doc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDatosProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDatosProfesorResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getDatosProfesorResponseBody Body;
        
        public getDatosProfesorResponse() {
        }
        
        public getDatosProfesorResponse(MvcApplication2.ServiceReference1.getDatosProfesorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDatosProfesorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDatosProfesorResult;
        
        public getDatosProfesorResponseBody() {
        }
        
        public getDatosProfesorResponseBody(string getDatosProfesorResult) {
            this.getDatosProfesorResult = getDatosProfesorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMateriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMaterias", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getMateriasRequestBody Body;
        
        public getMateriasRequest() {
        }
        
        public getMateriasRequest(MvcApplication2.ServiceReference1.getMateriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getMateriasRequestBody {
        
        public getMateriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMateriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMateriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getMateriasResponseBody Body;
        
        public getMateriasResponse() {
        }
        
        public getMateriasResponse(MvcApplication2.ServiceReference1.getMateriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMateriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMateriasResult;
        
        public getMateriasResponseBody() {
        }
        
        public getMateriasResponseBody(string getMateriasResult) {
            this.getMateriasResult = getMateriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGruposMateriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGruposMateria", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getGruposMateriaRequestBody Body;
        
        public getGruposMateriaRequest() {
        }
        
        public getGruposMateriaRequest(MvcApplication2.ServiceReference1.getGruposMateriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGruposMateriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_materia;
        
        public getGruposMateriaRequestBody() {
        }
        
        public getGruposMateriaRequestBody(string cod_materia) {
            this.cod_materia = cod_materia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGruposMateriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGruposMateriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getGruposMateriaResponseBody Body;
        
        public getGruposMateriaResponse() {
        }
        
        public getGruposMateriaResponse(MvcApplication2.ServiceReference1.getGruposMateriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGruposMateriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGruposMateriaResult;
        
        public getGruposMateriaResponseBody() {
        }
        
        public getGruposMateriaResponseBody(string getGruposMateriaResult) {
            this.getGruposMateriaResult = getGruposMateriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInscritosGrupoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInscritosGrupo", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getInscritosGrupoRequestBody Body;
        
        public getInscritosGrupoRequest() {
        }
        
        public getInscritosGrupoRequest(MvcApplication2.ServiceReference1.getInscritosGrupoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInscritosGrupoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cod_materia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string grupo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ano;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string periodo;
        
        public getInscritosGrupoRequestBody() {
        }
        
        public getInscritosGrupoRequestBody(string cod_materia, string grupo, string ano, string periodo) {
            this.cod_materia = cod_materia;
            this.grupo = grupo;
            this.ano = ano;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInscritosGrupoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInscritosGrupoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcApplication2.ServiceReference1.getInscritosGrupoResponseBody Body;
        
        public getInscritosGrupoResponse() {
        }
        
        public getInscritosGrupoResponse(MvcApplication2.ServiceReference1.getInscritosGrupoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInscritosGrupoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getInscritosGrupoResult;
        
        public getInscritosGrupoResponseBody() {
        }
        
        public getInscritosGrupoResponseBody(string getInscritosGrupoResult) {
            this.getInscritosGrupoResult = getInscritosGrupoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSFacultadSaludSoapChannel : MvcApplication2.ServiceReference1.WSFacultadSaludSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSFacultadSaludSoapClient : System.ServiceModel.ClientBase<MvcApplication2.ServiceReference1.WSFacultadSaludSoap>, MvcApplication2.ServiceReference1.WSFacultadSaludSoap {
        
        public WSFacultadSaludSoapClient() {
        }
        
        public WSFacultadSaludSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSFacultadSaludSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFacultadSaludSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSFacultadSaludSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getEstudiantesMatriculados(MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest request) {
            return base.Channel.getEstudiantesMatriculados(request);
        }
        
        public string getEstudiantesMatriculados(string cod_carrera) {
            MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest inValue = new MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequestBody();
            inValue.Body.cod_carrera = cod_carrera;
            MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getEstudiantesMatriculados(inValue);
            return retVal.Body.getEstudiantesMatriculadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getEstudiantesMatriculadosAsync(MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest request) {
            return base.Channel.getEstudiantesMatriculadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getEstudiantesMatriculadosResponse> getEstudiantesMatriculadosAsync(string cod_carrera) {
            MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest inValue = new MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getEstudiantesMatriculadosRequestBody();
            inValue.Body.cod_carrera = cod_carrera;
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getEstudiantesMatriculadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getProfesoresActivosResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getProfesoresActivos(MvcApplication2.ServiceReference1.getProfesoresActivosRequest request) {
            return base.Channel.getProfesoresActivos(request);
        }
        
        public string getProfesoresActivos(string cod_depto) {
            MvcApplication2.ServiceReference1.getProfesoresActivosRequest inValue = new MvcApplication2.ServiceReference1.getProfesoresActivosRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getProfesoresActivosRequestBody();
            inValue.Body.cod_depto = cod_depto;
            MvcApplication2.ServiceReference1.getProfesoresActivosResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getProfesoresActivos(inValue);
            return retVal.Body.getProfesoresActivosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getProfesoresActivosResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getProfesoresActivosAsync(MvcApplication2.ServiceReference1.getProfesoresActivosRequest request) {
            return base.Channel.getProfesoresActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getProfesoresActivosResponse> getProfesoresActivosAsync(string cod_depto) {
            MvcApplication2.ServiceReference1.getProfesoresActivosRequest inValue = new MvcApplication2.ServiceReference1.getProfesoresActivosRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getProfesoresActivosRequestBody();
            inValue.Body.cod_depto = cod_depto;
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getProfesoresActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getDatosEstudianteResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getDatosEstudiante(MvcApplication2.ServiceReference1.getDatosEstudianteRequest request) {
            return base.Channel.getDatosEstudiante(request);
        }
        
        public string getDatosEstudiante(string num_doc) {
            MvcApplication2.ServiceReference1.getDatosEstudianteRequest inValue = new MvcApplication2.ServiceReference1.getDatosEstudianteRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getDatosEstudianteRequestBody();
            inValue.Body.num_doc = num_doc;
            MvcApplication2.ServiceReference1.getDatosEstudianteResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getDatosEstudiante(inValue);
            return retVal.Body.getDatosEstudianteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getDatosEstudianteResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getDatosEstudianteAsync(MvcApplication2.ServiceReference1.getDatosEstudianteRequest request) {
            return base.Channel.getDatosEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getDatosEstudianteResponse> getDatosEstudianteAsync(string num_doc) {
            MvcApplication2.ServiceReference1.getDatosEstudianteRequest inValue = new MvcApplication2.ServiceReference1.getDatosEstudianteRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getDatosEstudianteRequestBody();
            inValue.Body.num_doc = num_doc;
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getDatosEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getDatosProfesorResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getDatosProfesor(MvcApplication2.ServiceReference1.getDatosProfesorRequest request) {
            return base.Channel.getDatosProfesor(request);
        }
        
        public string getDatosProfesor(string num_doc) {
            MvcApplication2.ServiceReference1.getDatosProfesorRequest inValue = new MvcApplication2.ServiceReference1.getDatosProfesorRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getDatosProfesorRequestBody();
            inValue.Body.num_doc = num_doc;
            MvcApplication2.ServiceReference1.getDatosProfesorResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getDatosProfesor(inValue);
            return retVal.Body.getDatosProfesorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getDatosProfesorResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getDatosProfesorAsync(MvcApplication2.ServiceReference1.getDatosProfesorRequest request) {
            return base.Channel.getDatosProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getDatosProfesorResponse> getDatosProfesorAsync(string num_doc) {
            MvcApplication2.ServiceReference1.getDatosProfesorRequest inValue = new MvcApplication2.ServiceReference1.getDatosProfesorRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getDatosProfesorRequestBody();
            inValue.Body.num_doc = num_doc;
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getDatosProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getMateriasResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getMaterias(MvcApplication2.ServiceReference1.getMateriasRequest request) {
            return base.Channel.getMaterias(request);
        }
        
        public string getMaterias() {
            MvcApplication2.ServiceReference1.getMateriasRequest inValue = new MvcApplication2.ServiceReference1.getMateriasRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getMateriasRequestBody();
            MvcApplication2.ServiceReference1.getMateriasResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getMaterias(inValue);
            return retVal.Body.getMateriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getMateriasResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getMateriasAsync(MvcApplication2.ServiceReference1.getMateriasRequest request) {
            return base.Channel.getMateriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getMateriasResponse> getMateriasAsync() {
            MvcApplication2.ServiceReference1.getMateriasRequest inValue = new MvcApplication2.ServiceReference1.getMateriasRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getMateriasRequestBody();
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getMateriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getGruposMateriaResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getGruposMateria(MvcApplication2.ServiceReference1.getGruposMateriaRequest request) {
            return base.Channel.getGruposMateria(request);
        }
        
        public string getGruposMateria(string cod_materia) {
            MvcApplication2.ServiceReference1.getGruposMateriaRequest inValue = new MvcApplication2.ServiceReference1.getGruposMateriaRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getGruposMateriaRequestBody();
            inValue.Body.cod_materia = cod_materia;
            MvcApplication2.ServiceReference1.getGruposMateriaResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getGruposMateria(inValue);
            return retVal.Body.getGruposMateriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getGruposMateriaResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getGruposMateriaAsync(MvcApplication2.ServiceReference1.getGruposMateriaRequest request) {
            return base.Channel.getGruposMateriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getGruposMateriaResponse> getGruposMateriaAsync(string cod_materia) {
            MvcApplication2.ServiceReference1.getGruposMateriaRequest inValue = new MvcApplication2.ServiceReference1.getGruposMateriaRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getGruposMateriaRequestBody();
            inValue.Body.cod_materia = cod_materia;
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getGruposMateriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication2.ServiceReference1.getInscritosGrupoResponse MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getInscritosGrupo(MvcApplication2.ServiceReference1.getInscritosGrupoRequest request) {
            return base.Channel.getInscritosGrupo(request);
        }
        
        public string getInscritosGrupo(string cod_materia, string grupo, string ano, string periodo) {
            MvcApplication2.ServiceReference1.getInscritosGrupoRequest inValue = new MvcApplication2.ServiceReference1.getInscritosGrupoRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getInscritosGrupoRequestBody();
            inValue.Body.cod_materia = cod_materia;
            inValue.Body.grupo = grupo;
            inValue.Body.ano = ano;
            inValue.Body.periodo = periodo;
            MvcApplication2.ServiceReference1.getInscritosGrupoResponse retVal = ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getInscritosGrupo(inValue);
            return retVal.Body.getInscritosGrupoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getInscritosGrupoResponse> MvcApplication2.ServiceReference1.WSFacultadSaludSoap.getInscritosGrupoAsync(MvcApplication2.ServiceReference1.getInscritosGrupoRequest request) {
            return base.Channel.getInscritosGrupoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcApplication2.ServiceReference1.getInscritosGrupoResponse> getInscritosGrupoAsync(string cod_materia, string grupo, string ano, string periodo) {
            MvcApplication2.ServiceReference1.getInscritosGrupoRequest inValue = new MvcApplication2.ServiceReference1.getInscritosGrupoRequest();
            inValue.Body = new MvcApplication2.ServiceReference1.getInscritosGrupoRequestBody();
            inValue.Body.cod_materia = cod_materia;
            inValue.Body.grupo = grupo;
            inValue.Body.ano = ano;
            inValue.Body.periodo = periodo;
            return ((MvcApplication2.ServiceReference1.WSFacultadSaludSoap)(this)).getInscritosGrupoAsync(inValue);
        }
    }
}
